### ISSUE TITLE
PermissionError: [Errno 13] Permission denied: 'dot'

### ISSUE THREAD

**Issue by gitpetyr** [hjalti/mossum#11]
```
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.10/bin//mossum", line 9, in <module>
    mossum.main()
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/mossum/mossum.py", line 294, in main
    image(res, i+1, label=args.title)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/mossum/mossum.py", line 266, in image
    graph.write(filename, format=args.format)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/pydot/core.py", line 1662, in write
    s = self.create(prog, format, encoding=encoding)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/pydot/core.py", line 1753, in create
    stdout_data, stderr_data, process = call_graphviz(
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/pydot/core.py", line 133, in call_graphviz
    process = subprocess.Popen(
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/subprocess.py", line 971, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/subprocess.py", line 1863, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
PermissionError: [Errno 13] Permission denied: 'dot'
```

**Comment by hjalti** [comment]
Sounds like you do not have dot installed or do not have permission to run the executable.

- Make sure graphviz is installed (https://graphviz.org/download/)
- Make sure the dot executable is accessible on your PATH (`which dot`)
