### ISSUE TITLE
Exception when generating image

### ISSUE THREAD

**Issue by nchristensen** [hjalti/mossum#2]
I get the following exception on Linux and Windows when attempting to generate an image. It might be something simple. 

`$ mossum http://moss.stanford.edu/results/xxxxxxxxx/index.html
Generating image for moss_xx-xx-xxxx_xxxxxx
Traceback (most recent call last):
  File "C:\Users\<user name>\Anaconda3\lib\site-packages\pydot.py", line 1878, in create
    stderr=subprocess.PIPE, stdout=subprocess.PIPE)
  File "C:\Users\<user name>\Anaconda3\lib\subprocess.py", line 947, in __init__
    restore_signals, start_new_session)
  File "C:\Users\<user name>\Anaconda3\lib\subprocess.py", line 1224, in _execute_child
    startupinfo)
FileNotFoundError: [WinError 2] The system cannot find the file specified

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:/Users/<user name>/Anaconda3/Scripts/mossum", line 9, in <module>
    mossum.main()
  File "C:\Users\<user name>\Anaconda3\lib\site-packages\mossum\mossum.py", line 251, in main
    image(res)
  File "C:\Users\<user name>\Anaconda3\lib\site-packages\mossum\mossum.py", line 222, in image
    graph.write(filename, format=args.format)
  File "C:\Users\<user name>\Anaconda3\lib\site-packages\pydot.py", line 1774, in write
    s = self.create(prog, format)
  File "C:\Users\<user name>\Anaconda3\lib\site-packages\pydot.py", line 1883, in create
    prog=prog))
Exception: "dot.exe" not found in path.`

**Comment by zdzc** [comment]
I had the same problem earlier. Installing graphviz fix the problem for me.

**Comment by tcibinan** [comment]
Just to make things clearer. As @zdzc mentioned you should install `graphviz` using your package manager. I was stuck trying to install graphviz using `pip`.
```bash
sudo apt install graphviz
```

**Comment by FlynnMc** [comment]
Is there a way to get around this without needing to install graphviz through brew/conda? I'm having the same issue on Mac and I need to avoid using homebrew/anaconda in the file. I found the pip version of graphviz doesn't work either.

**Comment by hjalti** [comment]
@FlynnMc No, not that I am aware of.

**Comment by jakob1379** [comment]
You can just download it, compile if necessary and add it to your path.
